# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec4c9b405cf4d9d1c1d69987a31f3df54aa1a40a363dfd4ef4e961f032cf9af8eb581ee8e652ea9c504eb21579a6e0dc1cb343f9c93e752182c0ecf9bc87a31

test:
  secret_key_base: caa9181f36ea277563be5ca5e3b8b8a6a45fea6fc3825562156d6f2d147ac7411f259947a0a8397f1e853a842e224f4dad8b8bdf492970a324d878d9f7e76db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
